Repository reactcostarica/website, pull requests merged in 2019-08, with the labels that each got.

#3 fix(progressive web app): fix gatsby-plugin-manifest config
  gatsby-config.js
Labels: bug

#5 Add Styled System
  .eslintrc.js
  .eslintrc.json
  gatsby-config.js
  gatsby/meta.js
  gatsby/plugins.js
  package.json
  src/components/box.tsx
  src/components/link.tsx
  src/config/theme/colors.ts
  src/config/theme/index.ts
  src/config/theme/space.ts
  src/layouts/app/footer.jsx
  src/layouts/app/footer.tsx
  src/layouts/app/index.tsx
  yarn.lock
Labels: enhancement

#6 Fix layout min-height
  package.json
  src/components/box.tsx
  src/hooks/viewport/index.ts
  src/layouts/app/index.tsx
  yarn.lock
Labels: bug

#7 refactor(components): move components to individual folders
  src/components/box/index.tsx
  src/components/link/index.tsx
  src/components/seo/index.tsx
  src/components/theme/index.tsx
  src/layouts/app/index.tsx
Labels: refactor

#8 Add material-ui
  gatsby/plugins.js
  package.json
  src/components/box/index.tsx
  src/components/link/index.tsx
  src/components/theme/index.tsx
  src/config/theme.ts
  src/config/theme/colors.ts
  src/config/theme/index.ts
  src/config/theme/space.ts
  src/layout/footer/index.tsx
  src/layout/index.tsx
  src/layout/theme/index.tsx
  src/layouts/app/footer.tsx
  src/pages/home/index.tsx
  yarn.lock
Labels: enhancement

#9 Add base layout
  src/components/link/index.tsx
  src/layout/footer/index.tsx
  src/layout/header/index.tsx
  src/layout/header/logo/index.tsx
  src/layout/index.tsx
  src/pages/404/index.tsx
  src/pages/home/index.tsx
Labels: enhancement

#10 Fix footer styling
  gatsby/plugins.js
  src/layout/index.tsx
Labels: bug

#12 Rename readme
  README.md
Labels: documentation
